version: '3.7'

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  node-exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"

  node-app:
    build: ./node-app
    ports:
      - "3000:3000"

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000" # Changed to avoid port conflict
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
