global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'ping-exporter'
    static_configs:
      - targets: ['ping-exporter:9427']

  - job_name: 'node-app'
    static_configs:
      - targets: ['node-app:3000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
